### ISSUE TITLE
Software Design Specification Document

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [Jay-ArBrouillard/Tournament-Bracket-Generator#28]
[SDSV1.0.docx](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3713880/SDSV1.0.docx)

**Comment by Jay-ArBrouillard** [comment]
Added all 3 diagrams to the SDS
[SDSV1.1.docx](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3779587/SDSV1.1.docx)

**Comment by Stealthheart** [comment]
[Tournament Bracket Generator.pdf](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3780231/Tournament.Bracket.Generator.pdf)

**Comment by Stealthheart** [comment]
[Tournament_Bracket_Generator_v2.0.pdf](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3780281/Tournament_Bracket_Generator_v2.0.pdf)
