### ISSUE TITLE
Coding Standards Document

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [Jay-ArBrouillard/Tournament-Bracket-Generator#51]
[CodingStandardsV1.docx](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3759566/CodingStandardsV1.docx)

Team4
Coding Standards
1.	PascalCase: Namespace, Class, Type, Interface, Property, and Enum
2.	camelCase: Method Names, Field Variables, and Parameter Names
3.	Curly Braces: Opening and Curly braces belong on separate line
4.	Line length: No lines longer than 70 characters
5.	Indentation: Single Tabs (4 spaces)
6.	Commenting Style: Stick to 1 line comments if possible, if block level comments are required then the code may need to be refactored to be more self-explanatory
7.	Exception-handling: Use a try-catch statement for most exception handling. If the only code in the “finally” block is a call to Dispose or Close something use a “using” statement to simplify.
8.	Class Sizes: Less than 30 methods.
9.	Method Sizes: Small as possible. The max size is the number of lines that can fit on one screen which is less than 100 lines of code, ideally less than 50 lines.
10.	SQL Table Names: Capitalized and plural 
11.	SQL Column Names: lowercase and compound words separated by underscore

**Comment by Stealthheart** [comment]
Just changed some grammar stuff. Looks good overall.
[CodingStandardsV1.1.docx](https://github.com/Jay-ArBrouillard/Tournament-Bracket-Generator/files/3762698/CodingStandardsV1.1.docx)
